name: Gradle Dokka
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gradle:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: gradle
          check-latest: true
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle dokkaHtml
        run: ./gradlew dokkaHtml
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: build/dokka/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
